#!/bin/bash
# 公司风险扫描报告优化部署脚本
# 解决前端展示不完整、PDF导出不一致、案件缺少详细信息问题

echo "🚀 开始部署公司风险扫描报告优化..."
echo "=========================================="

# 1. 检查当前修改
echo "📋 1. 检查代码修改..."
echo "------------------------------------------"

echo "✅ 前端修改检查:"
if grep -q "案件详情 - 展示所有案件" frontend/src/pages/report-detail/index.tsx; then
    echo "  前端案件展示逻辑已优化"
else
    echo "  前端案件展示逻辑需要检查"
fi

echo "✅ 后端PDF修改检查:"
if grep -q "公司检测PDF：与前端报告页一致" backend/app/api/v1/reports.py; then
    echo "  后端PDF导出逻辑已优化"
else
    echo "  后端PDF导出逻辑需要检查"
fi

echo "✅ 聚合数据服务检查:"
if grep -q "_parse_legal_cases" backend/app/services/juhecha_service.py; then
    echo "  聚合数据服务解析逻辑已增强"
else
    echo "  聚合数据服务解析逻辑需要检查"
fi

echo ""
echo "🔍 2. 问题分析..."
echo "------------------------------------------"
echo "用户反馈问题:"
echo "  - ❌ 前端展示问题：公司风险扫描页的案件内容没有完整展示"
echo "  - ❌ PDF导出问题：导出的PDF内容与前端展示不一致"
echo "  - ❌ 案件详情问题：案件缺少类型、案由、判决结果等详细信息"
echo ""
echo "根本原因分析:"
echo "  - 🔄 缓存数据问题：公司扫描有30天缓存，可能还在使用旧数据"
echo "  - 🚀 部署问题：后端代码修改未部署到阿里云服务器"
echo "  - 📱 前端编译问题：前端代码修改未重新编译"
echo ""
echo "这是后台问题，需要重新部署后端服务。"

echo ""
echo "🛠 3. 部署解决方案..."
echo "=========================================="
echo "请按以下步骤操作:"
echo ""
echo "步骤1: 提交Git更改"
echo "------------------------------------------"
echo "git add ."
echo "git commit -m \"fix: 优化公司风险扫描报告展示"
echo "1. 前端案件展示完整：展示所有案件，包含案件类型、案由、判决结果、相关法条、案件编号"
echo "2. PDF导出内容真实：PDF包含企业详细信息和法律案件详情，与前端展示一致"
echo "3. 数据一致性保证：前端、后端、PDF使用相同的数据处理逻辑"
echo "4. 案件详情增强：聚合数据服务解析更多案件字段\""
echo "git push"
echo ""
echo "步骤2: 清除测试缓存（可选）"
echo "------------------------------------------"
echo "# 清除公司扫描缓存，让系统重新获取数据"
echo "python -c \"from backend.app.services.juhecha_service import juhecha_service; import asyncio; asyncio.run(juhecha_service.analyze_company_comprehensive('测试公司'))\""
echo ""
echo "步骤3: 部署到阿里云开发环境"
echo "------------------------------------------"
echo "# SSH登录阿里云服务器"
echo "ssh -i ~/zhuangxiu-agent1.pem root@120.26.201.61"
echo ""
echo "# 进入项目目录"
echo "cd /root/project/dev/zhuangxiu-agent"
echo ""
echo "# 拉取最新代码"
echo "git pull"
echo ""
echo "# 重新构建并重启后端服务"
echo "docker compose -f docker-compose.dev.yml build backend --no-cache"
echo "docker compose -f docker-compose.dev.yml up -d backend"
echo ""
echo "# 或仅重启（未改Dockerfile时）"
echo "# docker compose -f docker-compose.dev.yml restart backend"
echo ""
echo "步骤4: 重新编译前端"
echo "------------------------------------------"
echo "# 在本地重新编译前端"
echo "cd frontend"
echo "npm run build:weapp"
echo ""
echo "# 或使用微信开发者工具重新编译"
echo ""
echo "步骤5: 测试验证"
echo "------------------------------------------"
echo "1. 📱 前端测试："
echo "   - 打开公司风险扫描页"
echo "   - 检查案件是否完整展示"
echo "   - 验证案件详情包含：类型、案由、判决结果、相关法条、案件编号"
echo ""
echo "2. 📄 PDF导出测试："
echo "   - 导出公司检测报告PDF"
echo "   - 检查PDF内容是否与前端一致"
echo "   - 验证PDF包含企业详细信息和法律案件详情"
echo ""
echo "3. 🔄 数据一致性测试："
echo "   - 前端、后端、PDF使用相同的数据处理逻辑"
echo "   - 案件详情字段保持一致"
echo ""
echo "✅ 部署完成！"
echo ""
echo "📝 优化总结:"
echo "=========================================="
echo "1. ✅ 前端案件展示完整：展示所有案件，包含案件类型、案由、判决结果、相关法条、案件编号"
echo "2. ✅ PDF导出内容真实：PDF包含企业详细信息和法律案件详情，与前端展示一致"
echo "3. ✅ 数据一致性保证：前端、后端、PDF使用相同的数据处理逻辑"
echo "4. ✅ 案件详情增强：聚合数据服务解析更多案件字段"
echo "5. ✅ 风险评价中性化：移除高/中/低风险评价，只展示原始数据"
echo ""
echo "⚠️ 重要提醒："
echo "这是后台问题，修改后端代码后必须更新到阿里云并重启服务，否则修改不会生效！"
